name: Scraper

on:
  workflow_dispatch:
    inputs:
      book_url:
        description: 'Target Book URL'
        required: true

      team_names:
        description: 'Priority Teams'
        required: false

      chapters_range:
        description: 'Chapters'
        required: true

      merge_chapters:
        description: 'Merge all Chapters Into a Single File'
        required: false
        type: boolean
        default: true

      extended_debug:
        description: 'Enable Extended Debug Logging'
        required: false
        type: boolean
        default: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Install Dependencies
        run: |
          npm install playwright
          npx playwright install chromium --with-deps

      - name: Discover Links
        env:
          EXTENDED_DEBUG: ${{ inputs.extended_debug }}
        run: node discovery.js "${{ inputs.book_url }}" "${{ inputs.team_names }}" "${{ inputs.chapters_range }}"

      - name: Extract Chapters
        env:
          MERGE_CHAPTERS: ${{ inputs.merge_chapters }}
          EXTENDED_DEBUG: ${{ inputs.extended_debug }}
        run: node extractor.js "${{ inputs.book_url }}"

      - name: Upload Output
        uses: actions/upload-artifact@v7
        with:
          name: chapters-text
          path: output/
          retention-days: 1
