name: RanobeLIB Scraper

on:
  workflow_dispatch:
    inputs:
      book_url:
        description: 'Target Book URL'
        required: true

      team_names:
        description: 'Priority Teams'
        required: false

      chapters_range:
        description: 'Chapters'
        required: true

      merge_chapters:
        description: 'Merge all Chapters Into a Single File'
        required: false
        type: boolean
        default: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install playwright playwright-extra puppeteer-extra-plugin-stealth
          npx playwright install chromium --with-deps

      - name: Discover Links
        run: node discovery.js "${{ inputs.book_url }}" "${{ inputs.team_names }}" "${{ inputs.chapters_range }}"

      - name: Extract Chapters
        env:
          MERGE_CHAPTERS: ${{ inputs.merge_chapters }}
        run: node extractor.js "${{ inputs.book_url }}"

      - name: Upload Output
        uses: actions/upload-artifact@v6
        with:
          name: chapters-text
          path: output/
          retention-days: 1
